# Three-Address Code (TAC) - Optimized
# Generated by Minimal C Compiler
# Optimizations applied: Constant folding, Copy propagation
# ─────────────────────────────────────

 1: DECL x
 2: DECL y
 3: DECL z
 4: PRINT 1
 5: PRINT 5
 6: PRINT 6
