# Three-Address Code (TAC) - Unoptimized
# Generated by Minimal C Compiler
# ─────────────────────────────────────

 1: DECL x
 2: DECL y
 3: DECL z
 4: x = 1
 5: PRINT x
 6: y = 2
 7: x = 3
 8: t0 = x + y
 9: z = t0
10: PRINT z
11: t1 = z + 1
12: z = t1
13: PRINT z
