# Three-Address Code (TAC) - Unoptimized
# Generated by Minimal C Compiler
# ─────────────────────────────────────

 1: DECL x
 2: DECL y
 3: DECL z
 4: x = 1
 5: y = 2
 6: t0 = x + y
 7: z = t0
 8: PRINT z
