# Three-Address Code (TAC) - Unoptimized
# Generated by Minimal C Compiler
# ─────────────────────────────────────

 1: DECL x
 2: DECL y
 3: DECL z
 4: x = 5
 5: y = 10
 6: z = 3
 7: t0 = x + y
 8: x = t0
 9: PRINT x
