# Three-Address Code (TAC) - Optimized
# Generated by Minimal C Compiler
# Optimizations applied: Constant folding, Copy propagation
# ─────────────────────────────────────

 1: DECL x
 2: DECL y
 3: DECL z
 4: x = 1
 5: y = 2
 6: t0 = 3
 7: z = 3
 8: PRINT 3
